using AutoGeneratedSubstitutes.Abstracts;
using FluentAssertions;
using Xunit;

namespace AutoGeneratedSubstitutes
{
    public class AutoMocksExample
    {
        [Theory, AutoNSubstitute]
        public void Injects_ready_to_use_mocks(IPerson mockedPerson)
        {
            mockedPerson.Name.Should().NotBeNull();
            mockedPerson.Surname.Should().NotBeNull();
        }

        [Theory, AutoNSubstitute]
        public void Can_go_even_deeper(ISomething something)
        {
            something.Should().NotBeNull();
            something.Level1.Should().NotBeNull();
            something.Level1.Level2.Should().NotBeNull();
        }
    }
}
